services:
  app:
    build: .
    container_name: flow_cmms
    environment:
      DATABASE_URL: postgresql://${CMMS_DB_USER:-flow_cmms_user}:${CMMS_DB_PASSWORD:-cmms_password}@postgres:5432/${CMMS_DB_NAME:-flow_cmms_db}
      SECRET_KEY: ${SECRET_KEY:-change-this-secret-key-before-production}
      APP_ENV: ${APP_ENV:-production}
#   ports:
#     - "8001:8000"
    restart: unless-stopped
    networks:
      - web_network
      - postgres_network
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --workers 2

networks:
  web_network:
    external: true
  postgres_network:
    external: true
